#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 123
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 85
#define ALIAS_COUNT 0
#define TOKEN_COUNT 52
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 19
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 22

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_const = 3,
  anon_sym_EQ = 4,
  anon_sym_import = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_SEMI = 8,
  anon_sym_extern = 9,
  anon_sym_export = 10,
  anon_sym_fn = 11,
  anon_sym_COMMA = 12,
  anon_sym_COLON = 13,
  anon_sym_u8 = 14,
  anon_sym_u16 = 15,
  anon_sym_u32 = 16,
  anon_sym_u64 = 17,
  anon_sym_i8 = 18,
  anon_sym_i16 = 19,
  anon_sym_i32 = 20,
  anon_sym_i64 = 21,
  anon_sym_bool = 22,
  anon_sym_str = 23,
  anon_sym_LBRACK = 24,
  anon_sym_RBRACK = 25,
  anon_sym_LBRACE = 26,
  anon_sym_RBRACE = 27,
  anon_sym_var = 28,
  anon_sym_return = 29,
  anon_sym_if = 30,
  anon_sym_else = 31,
  anon_sym_while = 32,
  anon_sym_for = 33,
  anon_sym_in = 34,
  anon_sym_break = 35,
  anon_sym_continue = 36,
  anon_sym_EQ_EQ = 37,
  anon_sym_BANG_EQ = 38,
  anon_sym_LT = 39,
  anon_sym_LT_EQ = 40,
  anon_sym_GT = 41,
  anon_sym_GT_EQ = 42,
  anon_sym_PLUS = 43,
  anon_sym_DASH = 44,
  anon_sym_DOT = 45,
  sym_number_literal = 46,
  anon_sym_DQUOTE = 47,
  aux_sym_string_literal_token1 = 48,
  sym_escape_sequence = 49,
  anon_sym_true = 50,
  anon_sym_false = 51,
  sym_source_file = 52,
  sym__top_level_item = 53,
  sym_import_declaration = 54,
  sym_function_declaration = 55,
  sym_parameter_list = 56,
  sym_parameter = 57,
  sym_type = 58,
  sym_primitive_type = 59,
  sym_array_type = 60,
  sym_block = 61,
  sym__statement = 62,
  sym_variable_declaration = 63,
  sym_return_statement = 64,
  sym_if_statement = 65,
  sym_while_statement = 66,
  sym_for_statement = 67,
  sym_break_statement = 68,
  sym_continue_statement = 69,
  sym_expression_statement = 70,
  sym__expression = 71,
  sym_assignment_expression = 72,
  sym_parenthesized_expression = 73,
  sym_binary_expression = 74,
  sym_call_expression = 75,
  sym_member_expression = 76,
  sym_argument_list = 77,
  sym_string_literal = 78,
  sym_boolean_literal = 79,
  aux_sym_source_file_repeat1 = 80,
  aux_sym_parameter_list_repeat1 = 81,
  aux_sym_block_repeat1 = 82,
  aux_sym_argument_list_repeat1 = 83,
  aux_sym_string_literal_repeat1 = 84,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_const] = "const",
  [anon_sym_EQ] = "=",
  [anon_sym_import] = "import",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SEMI] = ";",
  [anon_sym_extern] = "extern",
  [anon_sym_export] = "export",
  [anon_sym_fn] = "fn",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_bool] = "bool",
  [anon_sym_str] = "str",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_var] = "var",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_DOT] = ".",
  [sym_number_literal] = "number_literal",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__top_level_item] = "_top_level_item",
  [sym_import_declaration] = "import_declaration",
  [sym_function_declaration] = "function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_primitive_type] = "primitive_type",
  [sym_array_type] = "array_type",
  [sym_block] = "block",
  [sym__statement] = "_statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_return_statement] = "return_statement",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_for_statement] = "for_statement",
  [sym_break_statement] = "break_statement",
  [sym_continue_statement] = "continue_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_call_expression] = "call_expression",
  [sym_member_expression] = "member_expression",
  [sym_argument_list] = "argument_list",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__top_level_item] = sym__top_level_item,
  [sym_import_declaration] = sym_import_declaration,
  [sym_function_declaration] = sym_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_array_type] = sym_array_type,
  [sym_block] = sym_block,
  [sym__statement] = sym__statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_return_statement] = sym_return_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_for_statement] = sym_for_statement,
  [sym_break_statement] = sym_break_statement,
  [sym_continue_statement] = sym_continue_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_member_expression] = sym_member_expression,
  [sym_argument_list] = sym_argument_list,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_item] = {
    .visible = false,
    .named = true,
  },
  [sym_import_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_break_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_continue_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_arguments = 2,
  field_body = 3,
  field_condition = 4,
  field_consequence = 5,
  field_end = 6,
  field_function = 7,
  field_left = 8,
  field_member = 9,
  field_name = 10,
  field_object = 11,
  field_parameters = 12,
  field_path = 13,
  field_return_type = 14,
  field_right = 15,
  field_start = 16,
  field_type = 17,
  field_value = 18,
  field_variable = 19,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_end] = "end",
  [field_function] = "function",
  [field_left] = "left",
  [field_member] = "member",
  [field_name] = "name",
  [field_object] = "object",
  [field_parameters] = "parameters",
  [field_path] = "path",
  [field_return_type] = "return_type",
  [field_right] = "right",
  [field_start] = "start",
  [field_type] = "type",
  [field_value] = "value",
  [field_variable] = "variable",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
  [4] = {.index = 7, .length = 3},
  [5] = {.index = 10, .length = 3},
  [6] = {.index = 13, .length = 4},
  [7] = {.index = 17, .length = 3},
  [8] = {.index = 20, .length = 4},
  [9] = {.index = 24, .length = 2},
  [10] = {.index = 26, .length = 2},
  [11] = {.index = 28, .length = 1},
  [12] = {.index = 29, .length = 2},
  [13] = {.index = 31, .length = 2},
  [14] = {.index = 33, .length = 2},
  [15] = {.index = 35, .length = 2},
  [16] = {.index = 37, .length = 2},
  [17] = {.index = 39, .length = 2},
  [18] = {.index = 41, .length = 2},
  [19] = {.index = 43, .length = 3},
  [20] = {.index = 46, .length = 3},
  [21] = {.index = 49, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_parameters, 2},
  [2] =
    {field_body, 3},
    {field_name, 1},
    {field_parameters, 2},
  [5] =
    {field_name, 2},
    {field_parameters, 3},
  [7] =
    {field_body, 4},
    {field_name, 2},
    {field_parameters, 3},
  [10] =
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 3},
  [13] =
    {field_body, 4},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 3},
  [17] =
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 4},
  [20] =
    {field_body, 5},
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 4},
  [24] =
    {field_name, 0},
    {field_type, 2},
  [26] =
    {field_arguments, 1},
    {field_function, 0},
  [28] =
    {field_name, 1},
  [29] =
    {field_left, 0},
    {field_right, 2},
  [31] =
    {field_member, 2},
    {field_object, 0},
  [33] =
    {field_name, 1},
    {field_path, 5},
  [35] =
    {field_name, 1},
    {field_value, 3},
  [37] =
    {field_name, 1},
    {field_type, 3},
  [39] =
    {field_condition, 2},
    {field_consequence, 4},
  [41] =
    {field_body, 4},
    {field_condition, 2},
  [43] =
    {field_name, 1},
    {field_type, 3},
    {field_value, 5},
  [46] =
    {field_alternative, 6},
    {field_condition, 2},
    {field_consequence, 4},
  [49] =
    {field_body, 6},
    {field_end, 5},
    {field_start, 3},
    {field_variable, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 3,
        '"', 34,
        '(', 14,
        ')', 15,
        '+', 29,
        ',', 17,
        '-', 30,
        '.', 31,
        '/', 2,
        ':', 18,
        ';', 16,
        '<', 25,
        '=', 13,
        '>', 27,
        '[', 19,
        '\\', 4,
        ']', 20,
        '{', 21,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == 'x') ADVANCE(7);
      if (lookahead == '"' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(38);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 3,
        '"', 34,
        '(', 14,
        ')', 15,
        '+', 29,
        ',', 17,
        '-', 30,
        '.', 31,
        '/', 2,
        ':', 18,
        ';', 16,
        '<', 25,
        '=', 13,
        '>', 27,
        '[', 19,
        ']', 20,
        '{', 21,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '}') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(37);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'c', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'r', 6,
        's', 7,
        't', 8,
        'u', 9,
        'v', 10,
        'w', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 'x') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(20);
      if (lookahead == '3') ADVANCE(21);
      if (lookahead == '6') ADVANCE(22);
      if (lookahead == '8') ADVANCE(23);
      if (lookahead == 'f') ADVANCE(24);
      if (lookahead == 'm') ADVANCE(25);
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == '1') ADVANCE(30);
      if (lookahead == '3') ADVANCE(31);
      if (lookahead == '6') ADVANCE(32);
      if (lookahead == '8') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(40);
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == '6') ADVANCE(44);
      END_STATE();
    case 21:
      if (lookahead == '2') ADVANCE(45);
      END_STATE();
    case 22:
      if (lookahead == '4') ADVANCE(46);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(47);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == '6') ADVANCE(51);
      END_STATE();
    case 31:
      if (lookahead == '2') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == '4') ADVANCE(53);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(58);
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(65);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(67);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 57:
      if (lookahead == 'k') ADVANCE(68);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 59:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 65:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 70:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 72:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 74:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(81);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 77:
      if (lookahead == 'u') ADVANCE(82);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(120),
    [sym__top_level_item] = STATE(67),
    [sym_import_declaration] = STATE(67),
    [sym_function_declaration] = STATE(67),
    [aux_sym_source_file_repeat1] = STATE(67),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_const] = ACTIONS(7),
    [anon_sym_extern] = ACTIONS(9),
    [anon_sym_export] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_for,
    ACTIONS(29), 1,
      anon_sym_break,
    ACTIONS(31), 1,
      anon_sym_continue,
    ACTIONS(33), 1,
      sym_number_literal,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(15), 2,
      anon_sym_const,
      anon_sym_var,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(59), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(4), 10,
      sym__statement,
      sym_variable_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
      sym_for_statement,
      sym_break_statement,
      sym_continue_statement,
      sym_expression_statement,
      aux_sym_block_repeat1,
  [69] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(50), 1,
      anon_sym_return,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(56), 1,
      anon_sym_while,
    ACTIONS(59), 1,
      anon_sym_for,
    ACTIONS(62), 1,
      anon_sym_break,
    ACTIONS(65), 1,
      anon_sym_continue,
    ACTIONS(68), 1,
      sym_number_literal,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(42), 2,
      anon_sym_const,
      anon_sym_var,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(59), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(3), 10,
      sym__statement,
      sym_variable_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
      sym_for_statement,
      sym_break_statement,
      sym_continue_statement,
      sym_expression_statement,
      aux_sym_block_repeat1,
  [138] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_for,
    ACTIONS(29), 1,
      anon_sym_break,
    ACTIONS(31), 1,
      anon_sym_continue,
    ACTIONS(33), 1,
      sym_number_literal,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(15), 2,
      anon_sym_const,
      anon_sym_var,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(59), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(3), 10,
      sym__statement,
      sym_variable_declaration,
      sym_return_statement,
      sym_if_statement,
      sym_while_statement,
      sym_for_statement,
      sym_break_statement,
      sym_continue_statement,
      sym_expression_statement,
      aux_sym_block_repeat1,
  [207] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(81), 15,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [235] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(85), 15,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [263] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_EQ,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_DOT,
    STATE(51), 1,
      sym_argument_list,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [296] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_SEMI,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym_block,
    STATE(91), 1,
      sym_type,
    STATE(73), 2,
      sym_primitive_type,
      sym_array_type,
    ACTIONS(99), 10,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_str,
  [331] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(105), 1,
      anon_sym_SEMI,
    STATE(76), 1,
      sym_block,
    STATE(88), 1,
      sym_type,
    STATE(73), 2,
      sym_primitive_type,
      sym_array_type,
    ACTIONS(99), 10,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_str,
  [366] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_else,
    ACTIONS(109), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(107), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [392] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_DOT,
    STATE(51), 1,
      sym_argument_list,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [422] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(113), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [445] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(117), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [468] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(121), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DOT,
  [491] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(125), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(129), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [537] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(133), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [560] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    ACTIONS(139), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(56), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(141), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [618] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(145), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [641] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(149), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [664] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(153), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [687] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(157), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [710] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number_literal,
      anon_sym_DQUOTE,
    ACTIONS(161), 11,
      anon_sym_const,
      anon_sym_var,
      anon_sym_return,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_break,
      anon_sym_continue,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [733] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(66), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [765] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(167), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [797] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [829] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(171), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(65), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [861] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(61), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [893] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(175), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(47), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [925] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    STATE(93), 1,
      sym_type,
    STATE(73), 2,
      sym_primitive_type,
      sym_array_type,
    ACTIONS(99), 10,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_str,
  [951] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(42), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [983] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(179), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(60), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1015] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(57), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1047] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    STATE(75), 1,
      sym_type,
    STATE(73), 2,
      sym_primitive_type,
      sym_array_type,
    ACTIONS(99), 10,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_str,
  [1073] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1105] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(62), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1137] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    STATE(101), 1,
      sym_type,
    STATE(73), 2,
      sym_primitive_type,
      sym_array_type,
    ACTIONS(99), 10,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_str,
  [1163] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(187), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1195] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      sym_number_literal,
    STATE(11), 1,
      sym_member_expression,
    ACTIONS(37), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(68), 7,
      sym__expression,
      sym_assignment_expression,
      sym_parenthesized_expression,
      sym_binary_expression,
      sym_call_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(191), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1248] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1269] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(195), 9,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1292] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(201), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1313] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(205), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1334] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(209), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1355] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(195), 7,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1380] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(217), 5,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 13,
      anon_sym_SEMI,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_str,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(223), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1447] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(227), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 13,
      anon_sym_SEMI,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_str,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1487] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(233), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1508] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 13,
      anon_sym_SEMI,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_bool,
      anon_sym_str,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1527] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(239), 11,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1548] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1577] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_block,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1603] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(247), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1627] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_SEMI,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1650] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_SEMI,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1673] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1696] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1719] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_SEMI,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1742] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
    ACTIONS(261), 1,
      anon_sym_const,
    ACTIONS(267), 1,
      anon_sym_fn,
    ACTIONS(264), 2,
      anon_sym_extern,
      anon_sym_export,
    STATE(64), 4,
      sym__top_level_item,
      sym_import_declaration,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
  [1765] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1788] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_SEMI,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1811] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_const,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      anon_sym_extern,
      anon_sym_export,
    STATE(64), 4,
      sym__top_level_item,
      sym_import_declaration,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
  [1834] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_COLON,
    ACTIONS(199), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(213), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(215), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(219), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1868] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1879] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1912] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 5,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1945] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1967] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1978] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 5,
      ts_builtin_sym_end,
      anon_sym_const,
      anon_sym_extern,
      anon_sym_export,
      anon_sym_fn,
  [1989] = 5,
    ACTIONS(302), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_DQUOTE,
    ACTIONS(306), 1,
      aux_sym_string_literal_token1,
    ACTIONS(309), 1,
      sym_escape_sequence,
    STATE(81), 1,
      aux_sym_string_literal_repeat1,
  [2005] = 5,
    ACTIONS(302), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_DQUOTE,
    ACTIONS(314), 1,
      aux_sym_string_literal_token1,
    ACTIONS(316), 1,
      sym_escape_sequence,
    STATE(83), 1,
      aux_sym_string_literal_repeat1,
  [2021] = 5,
    ACTIONS(302), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_DQUOTE,
    ACTIONS(320), 1,
      aux_sym_string_literal_token1,
    ACTIONS(322), 1,
      sym_escape_sequence,
    STATE(81), 1,
      aux_sym_string_literal_repeat1,
  [2037] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_identifier,
    ACTIONS(326), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      sym_parameter,
  [2050] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_RPAREN,
    ACTIONS(330), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_parameter_list_repeat1,
  [2063] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    ACTIONS(333), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym_argument_list_repeat1,
  [2076] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_RPAREN,
    ACTIONS(338), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      aux_sym_parameter_list_repeat1,
  [2089] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(340), 1,
      anon_sym_SEMI,
    STATE(70), 1,
      sym_block,
  [2102] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_EQ,
    ACTIONS(344), 1,
      anon_sym_SEMI,
    ACTIONS(346), 1,
      anon_sym_COLON,
  [2115] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(348), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_argument_list_repeat1,
  [2128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(350), 1,
      anon_sym_SEMI,
    STATE(79), 1,
      sym_block,
  [2141] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      anon_sym_COMMA,
    ACTIONS(352), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_parameter_list_repeat1,
  [2154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2162] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_parameter_list,
  [2172] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_identifier,
    STATE(99), 1,
      sym_parameter,
  [2182] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_block,
  [2192] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_parameter_list,
  [2202] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    STATE(112), 1,
      sym_string_literal,
  [2212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_block,
  [2230] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      anon_sym_EQ,
    ACTIONS(360), 1,
      anon_sym_SEMI,
  [2240] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym_block,
  [2250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      anon_sym_SEMI,
  [2257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      anon_sym_SEMI,
  [2264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      anon_sym_RBRACK,
  [2271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      anon_sym_LPAREN,
  [2278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      anon_sym_LPAREN,
  [2285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(372), 1,
      sym_identifier,
  [2292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      sym_identifier,
  [2299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      anon_sym_COLON,
  [2306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 1,
      anon_sym_LPAREN,
  [2313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      anon_sym_RPAREN,
  [2320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_identifier,
  [2327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      anon_sym_import,
  [2334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      sym_identifier,
  [2341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      anon_sym_SEMI,
  [2348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(390), 1,
      sym_identifier,
  [2355] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(392), 1,
      anon_sym_in,
  [2362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(394), 1,
      anon_sym_EQ,
  [2369] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(396), 1,
      ts_builtin_sym_end,
  [2376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(398), 1,
      sym_identifier,
  [2383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(400), 1,
      anon_sym_fn,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 69,
  [SMALL_STATE(4)] = 138,
  [SMALL_STATE(5)] = 207,
  [SMALL_STATE(6)] = 235,
  [SMALL_STATE(7)] = 263,
  [SMALL_STATE(8)] = 296,
  [SMALL_STATE(9)] = 331,
  [SMALL_STATE(10)] = 366,
  [SMALL_STATE(11)] = 392,
  [SMALL_STATE(12)] = 422,
  [SMALL_STATE(13)] = 445,
  [SMALL_STATE(14)] = 468,
  [SMALL_STATE(15)] = 491,
  [SMALL_STATE(16)] = 514,
  [SMALL_STATE(17)] = 537,
  [SMALL_STATE(18)] = 560,
  [SMALL_STATE(19)] = 595,
  [SMALL_STATE(20)] = 618,
  [SMALL_STATE(21)] = 641,
  [SMALL_STATE(22)] = 664,
  [SMALL_STATE(23)] = 687,
  [SMALL_STATE(24)] = 710,
  [SMALL_STATE(25)] = 733,
  [SMALL_STATE(26)] = 765,
  [SMALL_STATE(27)] = 797,
  [SMALL_STATE(28)] = 829,
  [SMALL_STATE(29)] = 861,
  [SMALL_STATE(30)] = 893,
  [SMALL_STATE(31)] = 925,
  [SMALL_STATE(32)] = 951,
  [SMALL_STATE(33)] = 983,
  [SMALL_STATE(34)] = 1015,
  [SMALL_STATE(35)] = 1047,
  [SMALL_STATE(36)] = 1073,
  [SMALL_STATE(37)] = 1105,
  [SMALL_STATE(38)] = 1137,
  [SMALL_STATE(39)] = 1163,
  [SMALL_STATE(40)] = 1195,
  [SMALL_STATE(41)] = 1227,
  [SMALL_STATE(42)] = 1248,
  [SMALL_STATE(43)] = 1269,
  [SMALL_STATE(44)] = 1292,
  [SMALL_STATE(45)] = 1313,
  [SMALL_STATE(46)] = 1334,
  [SMALL_STATE(47)] = 1355,
  [SMALL_STATE(48)] = 1380,
  [SMALL_STATE(49)] = 1407,
  [SMALL_STATE(50)] = 1426,
  [SMALL_STATE(51)] = 1447,
  [SMALL_STATE(52)] = 1468,
  [SMALL_STATE(53)] = 1487,
  [SMALL_STATE(54)] = 1508,
  [SMALL_STATE(55)] = 1527,
  [SMALL_STATE(56)] = 1548,
  [SMALL_STATE(57)] = 1577,
  [SMALL_STATE(58)] = 1603,
  [SMALL_STATE(59)] = 1627,
  [SMALL_STATE(60)] = 1650,
  [SMALL_STATE(61)] = 1673,
  [SMALL_STATE(62)] = 1696,
  [SMALL_STATE(63)] = 1719,
  [SMALL_STATE(64)] = 1742,
  [SMALL_STATE(65)] = 1765,
  [SMALL_STATE(66)] = 1788,
  [SMALL_STATE(67)] = 1811,
  [SMALL_STATE(68)] = 1834,
  [SMALL_STATE(69)] = 1857,
  [SMALL_STATE(70)] = 1868,
  [SMALL_STATE(71)] = 1879,
  [SMALL_STATE(72)] = 1890,
  [SMALL_STATE(73)] = 1901,
  [SMALL_STATE(74)] = 1912,
  [SMALL_STATE(75)] = 1923,
  [SMALL_STATE(76)] = 1934,
  [SMALL_STATE(77)] = 1945,
  [SMALL_STATE(78)] = 1956,
  [SMALL_STATE(79)] = 1967,
  [SMALL_STATE(80)] = 1978,
  [SMALL_STATE(81)] = 1989,
  [SMALL_STATE(82)] = 2005,
  [SMALL_STATE(83)] = 2021,
  [SMALL_STATE(84)] = 2037,
  [SMALL_STATE(85)] = 2050,
  [SMALL_STATE(86)] = 2063,
  [SMALL_STATE(87)] = 2076,
  [SMALL_STATE(88)] = 2089,
  [SMALL_STATE(89)] = 2102,
  [SMALL_STATE(90)] = 2115,
  [SMALL_STATE(91)] = 2128,
  [SMALL_STATE(92)] = 2141,
  [SMALL_STATE(93)] = 2154,
  [SMALL_STATE(94)] = 2162,
  [SMALL_STATE(95)] = 2172,
  [SMALL_STATE(96)] = 2182,
  [SMALL_STATE(97)] = 2192,
  [SMALL_STATE(98)] = 2202,
  [SMALL_STATE(99)] = 2212,
  [SMALL_STATE(100)] = 2220,
  [SMALL_STATE(101)] = 2230,
  [SMALL_STATE(102)] = 2240,
  [SMALL_STATE(103)] = 2250,
  [SMALL_STATE(104)] = 2257,
  [SMALL_STATE(105)] = 2264,
  [SMALL_STATE(106)] = 2271,
  [SMALL_STATE(107)] = 2278,
  [SMALL_STATE(108)] = 2285,
  [SMALL_STATE(109)] = 2292,
  [SMALL_STATE(110)] = 2299,
  [SMALL_STATE(111)] = 2306,
  [SMALL_STATE(112)] = 2313,
  [SMALL_STATE(113)] = 2320,
  [SMALL_STATE(114)] = 2327,
  [SMALL_STATE(115)] = 2334,
  [SMALL_STATE(116)] = 2341,
  [SMALL_STATE(117)] = 2348,
  [SMALL_STATE(118)] = 2355,
  [SMALL_STATE(119)] = 2362,
  [SMALL_STATE(120)] = 2369,
  [SMALL_STATE(121)] = 2376,
  [SMALL_STATE(122)] = 2383,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 17),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 17),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 5, 0, 18),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 5, 0, 18),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 7, 0, 21),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 7, 0, 21),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3, 0, 13),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_expression, 3, 0, 13),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 16),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 16),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 11),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 11),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 15),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 15),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_break_statement, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_break_statement, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_continue_statement, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continue_statement, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 7, 0, 19),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 7, 0, 19),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, 0, 20),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, 0, 20),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, 0, 12),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 2, 0, 10),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 2, 0, 10),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [267] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 5, 0, 4),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 5, 0, 6),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4, 0, 1),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_declaration, 8, 0, 14),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 3, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4, 0, 2),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 5, 0, 3),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 5, 0, 5),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, 0, 8),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, 0, 7),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [304] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [306] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [309] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [314] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [318] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [320] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [330] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 9),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [396] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jam(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
